name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  e2e-tests:
      name: Run Cypress Tests
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: Install Dependencies
          run: npm ci

        - name: Start Application
          run: npm run dev &
          env:
            CYPRESS_BASE_URL: 'http://localhost:3000'

        - name: Run Cypress e2e tests
          run: npx cypress run
          env:
            CYPRESS_BASE_URL: 'http://localhost:5173'
            VITE_BASE_URL: 'https://api.rawg.io/api'