name: Deploy to Azure

on:
  workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Azure Static Web Apps
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
      
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_OCEAN_01A52E803 }}
          action: "upload"
          app_location: "/"
          output_location: dist/